### ISSUE TITLE
Fix no server crash

### ISSUE THREAD

**Issue by xNilsson** [Jullekungfu/SpaceDefence#2]
Server crash when 4 players are playing. Opponent init is sent 5 times then all the players lose connection. Server gets nullpointer-exception in parsebytes:116.

Error might be that there aren't 4 bytes in the bytequeue. That the protocol isn't followed.

**Comment by Dolck** [comment]
Add details please...

**Comment by antonlin1** [comment]
Console print: 

Exception in thread "Thread-2" java.lang.NullPointerException
	at client.ParseBytes.bytesToInt(ParseBytes.java:154)
	at client.ParseBytes.run(ParseBytes.java:116)
NegativeArraySizeException when declaring msg.

**Comment by Dolck** [comment]
Works pretty well right now....
