### ISSUE TITLE
Game implementations

### ISSUE THREAD

**Issue by antonlin1** [Jullekungfu/SpaceDefence#5]
- ~~Key input when match ready to start~~
- Player collision detection
- Creep hp to be decreased when hit, not insta-kill
- ~~Creep spawn randomly(not to close to border)~~
- Set appropriate speed on objects
- Set appropriate size on objects
- ~~Add income~~
- ~~Players to have different colours~~
- ~~Players to be triangle shape~~

**Comment by antonlin1** [comment]
Done: 
Key input when match ready to start
Creep spawn randomly(not to close to border)
Players to have different colours
Players to be triangle shape

**Comment by Dolck** [comment]
I think everything here is implemented
